// getting user comments 

export const GETTING_USER_COMMENTS = "GETTING_USER_COMMENTS"
export const GET_USER_COMMENTS_SUCCESS = "GET_USER_COMMENTS_SUCCESS"
export const GET_USER_COMMENTS_ERROR = "GET_USER_COMMENTS_ERROR"


