export const GETTING_ALL_PRODUCTS = "GETTING_ALL_PRODUCTS"
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"
export const GET_ALL_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR"



export const ADDING_PRODUCT = "ADDING_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"


// get all comments for specific product 

export const GETTING_COMMENTS_FOR_PRODUCT = "GETTING_COMMENTS_FOR_PRODUCT"
export const GET_COMMENTS_FOR_PRODUCT_SUCCESS = "GET_COMMENTS_FOR_PRODUCT_SUCCESS"
export const GET_COMMENTS_FOR_PRODUCT_ERROR = "GET_COMMENTS_FOR_PRODUCT_ERROR"


// add comment for specific product by specific user


export const ADDING_COMMENT = "ADDING_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR"



// get all ratings for specific product 


export const GETTING_RATINGS_FOR_PRODUCT = "GETTING_RATINGS_FOR_PRODUCT"
export const GET_RATINGS_FOR_PRODUCT_SUCCESS = "GET_RATINGS_FOR_PRODUCT_SUCCESS"
export const GET_RATINGS_FOR_PRODUCT_ERROR = "GET_RATINGS_FOR_PRODUCT_ERROR"


// add rating 


export const ADDING_RATING = "ADDING_RATING"
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS"
export const ADD_RATING_ERROR = "ADD_RATING_ERROR"

