export const GETTING_ALL_PRODUCTS = "GETTING_ALL_PRODUCTS"
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"
export const GET_ALL_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR"



export const ADDING_PRODUCT = "ADDING_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"


// get all comments for specific product 

export const GETTING_COMMENTS_FOR_PRODUCT = "GETTING_COMMENTS_FOR_PRODUCT"
export const GET_COMMENTS_FOR_PRODUCT_SUCCESS = "GET_COMMENTS_FOR_PRODUCT_SUCCESS"
export const GET_COMMENTS_FOR_PRODUCT_ERROR = "GET_COMMENTS_FOR_PRODUCT_ERROR"


// add comment for specific product by specific user


export const ADDING_COMMENT = "ADDING_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR"



// get all ratings for specific product 


export const GETTING_RATINGS_FOR_PRODUCT = "GETTING_RATINGS_FOR_PRODUCT"
export const GET_RATINGS_FOR_PRODUCT_SUCCESS = "GET_RATINGS_FOR_PRODUCT_SUCCESS"
export const GET_RATINGS_FOR_PRODUCT_ERROR = "GET_RATINGS_FOR_PRODUCT_ERROR"


// add rating 


export const ADDING_RATING = "ADDING_RATING"
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS"
export const ADD_RATING_ERROR = "ADD_RATING_ERROR"



// edit product 


export const EDITING_PRODUCT = "EDITING_PRODUCT"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR"


// delete product

export const DELETING_PRODUCT = "DELETING_PRODUCT"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"



// edit comment 

export const EDITING_COMMENT = "EDITING_COMMENT"
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR"


// delete comment 

export const DELETING_COMMENT = "DELETING_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR"



// edit rating 

export const EDITING_RATING = "EDITING_RATING"
export const EDIT_RATING_SUCCESS = "EDIT_RATING_SUCCESS"
export const EDIT_RATING_ERROR = "EDIT_RATING_ERROR"


// delete rating 

export const DELETING_RATING = "DELETING_RATING"
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS"
export const DELETE_RATING_ERROR = "DELETE_RATING_ERROR"

